version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7 # don't adopt a release until it has been out for a week
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7 # don't adopt a release until it has been out for a week
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7 # don't adopt a release until it has been out for a week
