[google_cloud]
maps_api_key = "dummy"

[migration]
user = "chauffeur"
password = "dummy"
name = "chauffeur"
host = "localhost"
port = 1201
directory = "src/main/resources/db/migration"

[database]
user = "chauffeur"
password = "dummy"
name = "chauffeur"
host = "localhost"
port = 1201